name: rjs
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Data Layer
  get_it: ^5.0.1
  dio: ^3.0.10
  flutter_bloc: ^4.0.1
  built_value: ^7.1.0
  floor: ^0.14.0
  rxdart: ^0.24.1

  # UI Layer
  cupertino_icons: ^1.0.0
  carousel_slider: ^2.2.1
  cached_network_image: ^2.0.0
  persistent_bottom_nav_bar: ^3.1.0
  flutter_audio_query: ^0.3.5+6
  just_audio: ^0.4.4


  # utils
  flutter_screenutil: ^1.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.13.0
  build_runner: ^1.10.0
  built_value_generator: ^7.1.0


flutter:

  uses-material-design: true
  assets:
     - assets/images/
     - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        # https://fonts.google.com/specimen/Rock+Salt
        - asset: assets/montserrat/Montserrat-Black.otf
        - asset: assets/montserrat/Montserrat-Bold.otf
        - asset: assets/montserrat/Montserrat-ExtraBold.otf
        - asset: assets/montserrat/Montserrat-Hairline.otf
        - asset: assets/montserrat/Montserrat-Light.otf
        - asset: assets/montserrat/Montserrat-Regular.otf
        - asset: assets/montserrat/Montserrat-SemiBold.otf
        - asset: assets/montserrat/Montserrat-Thin.ttf
        - asset: assets/montserrat/Montserrat-UltraLight.otf
    - family: light
      fonts:
        - asset: assets/montserrat/Noteworthy-Lt.ttf
    - family: medium
      fonts:
         - asset: assets/montserrat/FontsFree-Net-Montserrat-Medium.ttf
    - family: semibold
      fonts:
         - asset: assets/montserrat/Montserrat-SemiBold.otf
    - family: light
      fonts:
        - asset: assets/montserrat/Montserrat-Light.otf